version: "3.7"

# Create a .env file, you can use env.sample as en example.
#
# RESTART_MODE=unless-stopped
# FQDN=pcah.example.com
# COCKPIT_URL=https://github.com/macno/json-against-humanity/raw/full-json/decks/full.json


services:
  be:
    image: buttonsagainsthumanity/bah-backend
    restart: ${RESTART_MODE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.be.rule=Host(`${FQDN}`) && Path(`/socket.io/`)
    environment:
      - COCKPIT_URL
  fe:
    image: buttonsagainsthumanity/bah-frontend
    restart: ${RESTART_MODE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.fe.rule=Host(`${FQDN}`)
  traefik:
    image: traefik:v2.2
    restart: ${RESTART_MODE}
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
