version: "3.7"

# Create a .env file, this is an example (verify on https://hub.docker.com/u/buttonsagainsthumanity latest versions)
# RESTART_MODE=unless-stopped
# FQDN=pcah.example.com
# BAH_BE_VERSION=0.2.3
# BAH_FE_VERSION=0.2.2

services:
  be:
    image: buttonsagainsthumanity/bah-backend:${BAH_BE_VERSION}
    restart: ${RESTART_MODE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.be.rule=Host(`${FQDN}`) && Path(`/socket.io/`)
  fe:
    image: buttonsagainsthumanity/bah-frontend:${BAH_FE_VERSION}
    restart: ${RESTART_MODE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.fe.rule=Host(`${FQDN}`)
  traefik:
    image: traefik:v2.2
    restart: ${RESTART_MODE}
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
